server:
  port: 8002

spring:
  application:
    name: file-analysis-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/analysis_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  file-storing-url: ${FILE_STORING_URL:http://localhost:8001}
  reports-dir: ${REPORTS_DIR:/app/reports}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
